apiVersion: v1
kind: Config
preferences: {}
clusters:
- cluster:
    server: https://cluster1.example.com:6443
    certificate-authority-data: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCM==
  name: cluster1
contexts:
- context:
    cluster: cluster1
    user: user1
    namespace: default
  name: context1
current-context: single-context
users:
- name: user1
  user:
    token: fake-token-single
